import axios from 'axios'
const API = axios.create({ baseURL: 'http://localhost:8080/api', headers: { 'Content-Type': 'application/json' } })
export const registerStudent        = (data)               => API.post('/students', data)
export const getAllStudents          = ()                   => API.get('/students')
export const getStudentById         = (id)                 => API.get(`/students/${id}`)
export const getStudentByEmail      = (email)              => API.get(`/students/email/${email}`)
export const updateStudent          = (id, data)           => API.put(`/students/${id}`, data)
export const deleteStudent          = (id)                 => API.delete(`/students/${id}`)
export const getReadinessScore      = (id)                 => API.get(`/students/${id}/readiness-score`)
export const getAllSkills            = ()                   => API.get('/skills')
export const addSkill               = (data)               => API.post('/skills', data)
export const addSkillToStudent      = (studentId, skillId, proficiency) => API.post(`/students/${studentId}/skills?skillId=${skillId}&proficiency=${proficiency}`)
export const removeSkillFromStudent = (studentId, skillId) => API.delete(`/students/${studentId}/skills/${skillId}`)
export const getStudentSkills       = (studentId)          => API.get(`/students/${studentId}/skills`)
export const addCertification       = (studentId, data)    => API.post(`/students/${studentId}/certifications`, data)
export const getCertifications      = (studentId)          => API.get(`/students/${studentId}/certifications`)
export const addInternship          = (studentId, data)    => API.post(`/students/${studentId}/internships`, data)
export const getInternships         = (studentId)          => API.get(`/students/${studentId}/internships`)
export const getAllCompanies         = ()                   => API.get('/companies')
export const addCompany             = (data)               => API.post('/companies', data)
export const addJobRole             = (companyId, data)    => API.post(`/companies/${companyId}/jobs`, data)
export const getAllJobs              = ()                   => API.get('/companies/all-jobs')
export const addSkillToJob          = (jobId, skillId, weightage) => API.post(`/companies/jobs/${jobId}/skills?skillId=${skillId}&weightage=${weightage}&mandatory=true`)
export const analyzeSkillGap        = (studentId, jobRoleId) => API.post(`/skill-gap/analyze?studentId=${studentId}&jobRoleId=${jobRoleId}`)
export const getReportsByStudent    = (studentId)          => API.get(`/skill-gap/student/${studentId}`)
export const getAllReports           = ()                   => API.get('/skill-gap/all')
export default API
